# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/winni/EigeneDateien/tmp/qt/qhexedit/trunk/sip/example/optionsdialog.ui'
#
# Created: Sat Aug 27 15:39:56 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_OptionsDialog(object):
    def setupUi(self, OptionsDialog):
        OptionsDialog.setObjectName(_fromUtf8("OptionsDialog"))
        OptionsDialog.resize(395, 351)
        self.verticalLayout = QtGui.QVBoxLayout(OptionsDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbFlags = QtGui.QGroupBox(OptionsDialog)
        self.gbFlags.setObjectName(_fromUtf8("gbFlags"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gbFlags)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cbAddressArea = QtGui.QCheckBox(self.gbFlags)
        self.cbAddressArea.setObjectName(_fromUtf8("cbAddressArea"))
        self.gridLayout_2.addWidget(self.cbAddressArea, 0, 0, 1, 1)
        self.cbOverwriteMode = QtGui.QCheckBox(self.gbFlags)
        self.cbOverwriteMode.setObjectName(_fromUtf8("cbOverwriteMode"))
        self.gridLayout_2.addWidget(self.cbOverwriteMode, 0, 1, 1, 1)
        self.cbAsciiArea = QtGui.QCheckBox(self.gbFlags)
        self.cbAsciiArea.setObjectName(_fromUtf8("cbAsciiArea"))
        self.gridLayout_2.addWidget(self.cbAsciiArea, 1, 0, 1, 1)
        self.cbHighlighting = QtGui.QCheckBox(self.gbFlags)
        self.cbHighlighting.setObjectName(_fromUtf8("cbHighlighting"))
        self.gridLayout_2.addWidget(self.cbHighlighting, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbFlags)
        self.gbColors = QtGui.QGroupBox(OptionsDialog)
        self.gbColors.setObjectName(_fromUtf8("gbColors"))
        self.gridLayout = QtGui.QGridLayout(self.gbColors)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pbHighlightingColor = QtGui.QPushButton(self.gbColors)
        self.pbHighlightingColor.setObjectName(_fromUtf8("pbHighlightingColor"))
        self.gridLayout.addWidget(self.pbHighlightingColor, 0, 0, 1, 1)
        self.lbHighlightingColor = QtGui.QLabel(self.gbColors)
        self.lbHighlightingColor.setMinimumSize(QtCore.QSize(100, 0))
        self.lbHighlightingColor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbHighlightingColor.setFrameShape(QtGui.QFrame.Panel)
        self.lbHighlightingColor.setFrameShadow(QtGui.QFrame.Sunken)
        self.lbHighlightingColor.setText(_fromUtf8(""))
        self.lbHighlightingColor.setObjectName(_fromUtf8("lbHighlightingColor"))
        self.gridLayout.addWidget(self.lbHighlightingColor, 0, 1, 1, 1)
        self.pbAddressAreaColor = QtGui.QPushButton(self.gbColors)
        self.pbAddressAreaColor.setObjectName(_fromUtf8("pbAddressAreaColor"))
        self.gridLayout.addWidget(self.pbAddressAreaColor, 1, 0, 2, 1)
        self.lbAddressAreaColor = QtGui.QLabel(self.gbColors)
        self.lbAddressAreaColor.setMinimumSize(QtCore.QSize(100, 0))
        self.lbAddressAreaColor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbAddressAreaColor.setFrameShape(QtGui.QFrame.Panel)
        self.lbAddressAreaColor.setFrameShadow(QtGui.QFrame.Sunken)
        self.lbAddressAreaColor.setText(_fromUtf8(""))
        self.lbAddressAreaColor.setObjectName(_fromUtf8("lbAddressAreaColor"))
        self.gridLayout.addWidget(self.lbAddressAreaColor, 1, 1, 2, 1)
        self.lbSelectionColor = QtGui.QLabel(self.gbColors)
        self.lbSelectionColor.setMinimumSize(QtCore.QSize(100, 0))
        self.lbSelectionColor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbSelectionColor.setFrameShape(QtGui.QFrame.Panel)
        self.lbSelectionColor.setFrameShadow(QtGui.QFrame.Sunken)
        self.lbSelectionColor.setText(_fromUtf8(""))
        self.lbSelectionColor.setObjectName(_fromUtf8("lbSelectionColor"))
        self.gridLayout.addWidget(self.lbSelectionColor, 3, 1, 1, 1)
        self.pbSelectionColor = QtGui.QPushButton(self.gbColors)
        self.pbSelectionColor.setObjectName(_fromUtf8("pbSelectionColor"))
        self.gridLayout.addWidget(self.pbSelectionColor, 3, 0, 1, 1)
        self.pbWidgetFont = QtGui.QPushButton(self.gbColors)
        self.pbWidgetFont.setObjectName(_fromUtf8("pbWidgetFont"))
        self.gridLayout.addWidget(self.pbWidgetFont, 4, 0, 1, 1)
        self.leWidgetFont = QtGui.QLineEdit(self.gbColors)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leWidgetFont.sizePolicy().hasHeightForWidth())
        self.leWidgetFont.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        self.leWidgetFont.setFont(font)
        self.leWidgetFont.setObjectName(_fromUtf8("leWidgetFont"))
        self.gridLayout.addWidget(self.leWidgetFont, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbColors)
        self.gbAddressAreaWidth = QtGui.QGroupBox(OptionsDialog)
        self.gbAddressAreaWidth.setObjectName(_fromUtf8("gbAddressAreaWidth"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gbAddressAreaWidth)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lbAddressAreaWidth = QtGui.QLabel(self.gbAddressAreaWidth)
        self.lbAddressAreaWidth.setObjectName(_fromUtf8("lbAddressAreaWidth"))
        self.gridLayout_3.addWidget(self.lbAddressAreaWidth, 0, 0, 1, 1)
        self.sbAddressAreaWidth = QtGui.QSpinBox(self.gbAddressAreaWidth)
        self.sbAddressAreaWidth.setMinimum(1)
        self.sbAddressAreaWidth.setMaximum(6)
        self.sbAddressAreaWidth.setProperty(_fromUtf8("value"), 4)
        self.sbAddressAreaWidth.setObjectName(_fromUtf8("sbAddressAreaWidth"))
        self.gridLayout_3.addWidget(self.sbAddressAreaWidth, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbAddressAreaWidth)
        spacerItem = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(OptionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(OptionsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), OptionsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), OptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialog)
        OptionsDialog.setTabOrder(self.cbOverwriteMode, self.cbAsciiArea)
        OptionsDialog.setTabOrder(self.cbAsciiArea, self.cbAddressArea)
        OptionsDialog.setTabOrder(self.cbAddressArea, self.cbHighlighting)
        OptionsDialog.setTabOrder(self.cbHighlighting, self.pbHighlightingColor)
        OptionsDialog.setTabOrder(self.pbHighlightingColor, self.pbAddressAreaColor)
        OptionsDialog.setTabOrder(self.pbAddressAreaColor, self.buttonBox)

    def retranslateUi(self, OptionsDialog):
        OptionsDialog.setWindowTitle(QtGui.QApplication.translate("OptionsDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.gbFlags.setTitle(QtGui.QApplication.translate("OptionsDialog", "Flags", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAddressArea.setText(QtGui.QApplication.translate("OptionsDialog", "Address Area", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOverwriteMode.setText(QtGui.QApplication.translate("OptionsDialog", "Overwrite Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAsciiArea.setText(QtGui.QApplication.translate("OptionsDialog", "Ascii Area", None, QtGui.QApplication.UnicodeUTF8))
        self.cbHighlighting.setText(QtGui.QApplication.translate("OptionsDialog", "Higlighting", None, QtGui.QApplication.UnicodeUTF8))
        self.gbColors.setTitle(QtGui.QApplication.translate("OptionsDialog", "Colors and Fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.pbHighlightingColor.setText(QtGui.QApplication.translate("OptionsDialog", "Highlighting Color", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddressAreaColor.setText(QtGui.QApplication.translate("OptionsDialog", "Address Area Color", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSelectionColor.setText(QtGui.QApplication.translate("OptionsDialog", "Selection Color", None, QtGui.QApplication.UnicodeUTF8))
        self.pbWidgetFont.setText(QtGui.QApplication.translate("OptionsDialog", "Widget Font", None, QtGui.QApplication.UnicodeUTF8))
        self.leWidgetFont.setText(QtGui.QApplication.translate("OptionsDialog", "01 23 45 67 89 ab cd ef", None, QtGui.QApplication.UnicodeUTF8))
        self.gbAddressAreaWidth.setTitle(QtGui.QApplication.translate("OptionsDialog", "Address Area", None, QtGui.QApplication.UnicodeUTF8))
        self.lbAddressAreaWidth.setText(QtGui.QApplication.translate("OptionsDialog", "Address Area Width", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    OptionsDialog = QtGui.QDialog()
    ui = Ui_OptionsDialog()
    ui.setupUi(OptionsDialog)
    OptionsDialog.show()
    sys.exit(app.exec_())

