[build-system]
requires = ["sip >=6.9, <7", "PyQt-builder >=1.17, <2", "PyQt6"]
build-backend = "sipbuild.api"

[project]
name = "PyQt6-QHexEdit"
classifiers = [
    "Development Status :: 5 - Production/Stable", 
    "Environment :: X11 Applications :: Qt",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Embedded Systems",
    "Topic :: Utilities",
]
keywords = [
    "Development",
    "Binary",
    "Editor",
    "Hex Editor",
    "Viewer",
]
version = "0.9.0"
description = "Python bindings for the QHexEdit Widget"
readme = "readme.md"
urls.homepage = "https://github.com/Simsys/qhexedit2"
dependencies = ["PyQt6 (>=6.2.0)"]
license = { text = "LGPL-2.1-only" }
requires-python = ">=3.8"
authors = [{ name = "Winfried Simon", email = "winfried.simon@gmail.com" }]

[tool.sip]
project-factory = "pyqtbuild:PyQtProject"

[tool.sip.project]
name = "pyqt6-qhexedit"
sip-include-dirs = ["bindings"]
sip-files-dir = "."
tag-prefix = "QHexEdit"

[tool.sip.bindings.QHexEdit]
qmake-QT = ["widgets"]
include-dirs = ["src"]
sip-file = "QHexEdit.sip"
headers = [
    "src/chunks.h",
    "src/commands.h",
    "src/qhexedit.h",
    "src/color_manager.h",
]
sources = [
    "src/chunks.cpp",
    "src/commands.cpp",
    "src/qhexedit.cpp",
    "src/color_manager.cpp",
]
