name: Windows Release

on: [push]

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   5.15.2
  ARTIFACT:     qhexedit.zip

jobs:
  build:
    runs-on:  windows-2019

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v4

      - name: (2) Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version:      ${{ env.QT_VERSION }}
          host:         windows
          target:       desktop
          arch:         win64_msvc2019_64
          dir:          ${{ runner.temp }}
          setup-python: false

      - name: (3) list files
        run: |
          dir ${{ github.workspace }}
          dir ${{ env.SOURCE_DIR }}

      - name: (4) Create build directory
        run:  mkdir ${{ runner.temp }}\build

      - name: (5) Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
        
      - name: (6) Build
        working-directory: ${{ runner.temp }}\build
        run:  |
          qmake ${{ env.SOURCE_DIR }}\example\qhexedit.pro
          nmake release
          dir
          cd release 
          dir
          cd..
            
      - name: (9) Zip build
        working-directory: ${{ runner.temp }}
        run:  |
              7z a qhexedit.zip ${{ runner.temp }}\build\* -r
              
      - name: (10) Save build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}\${{ env.ARTIFACT }}