name: Windows Qt5 PyQt Wheel

on:
  workflow_call:

defaults:
  run:
    shell: cmd

jobs:
  build:
    runs-on:  windows-2019

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version:      5.15.2
          host:         windows
          target:       desktop
          arch:         win64_msvc2019_64
          dir:          ${{ runner.temp }}
          setup-python: false

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
        
      - name: Make Python Wheel
        working-directory: ${{ runner.temp }}
        run: |
          python -m pip install build
          mkdir python
          cd python
          xcopy ${{ github.workspace }}\src src\
          copy ${{ github.workspace }}\license.txt .
          copy ${{ github.workspace }}\readme.md .
          copy ${{ github.workspace }}\python\pyqt5-pyproject.toml pyproject.toml
          copy ${{ github.workspace }}\python\QHexEdit.sip .

          python -m build --verbose

      - name: Save Python Wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-qt5-windows
          path: ${{ runner.temp }}\python\dist\*.whl