name: Make Qt6 Wheels

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    uses: ./.github/workflows/wheel-qt6-linux.yml

  build-windows:
    uses: ./.github/workflows/wheel-qt6-windows.yml

  merge:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: pyqt6-dist
          delete-merged: true
