name: Make Qt5 Wheels

on:
  push:
    tags:
      - 'v*'

jobs:

  build-linux:
    uses: ./.github/workflows/wheel-qt5-linux.yml

  build-windows:
    uses: ./.github/workflows/wheel-qt5-windows.yml

  merge:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: pyqt5-dist
          delete-merged: true
